export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const ADMIN_LOADED = 'ADMIN_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

//admin actions
export const ADD_PORTFOLIO = 'ADD_PORTFOLIO';
export const EDIT_PORTFOLIO = "EDIT_PORTFOLIO";
export const DELETE_PORTFOLIO = "DELETE_PORTFOLIO";

export const ADD_IMAGE = 'ADD_IMAGE';
export const EDIT_IMAGE = "EDIT_IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const PORTFOLIO_ERROR = 'PORTFOLIO_ERROR';
export const IMAGE_ERROR = 'IMAGE_ERROR';

//store actions
export const LOAD_IMAGES = 'LOAD_IMAGES';
export const LOAD_GALLERY = 'LOAD_GALLERY';
export const LOAD_PORTFOLIOS = 'LOAD_PORTFOLIOS';
export const GET_IMAGE = "GET_IMAGE";
export const GET_PORTFOLIO = "GET_PORTFOLIO";
export const GET_SELECTED_ARTWORK = "GET_SELECTED_ARTWORK";
export const CLEAR_SELECTED_ARTWORK = "CLEAR_SELECTED_ARTWORK";
export const GET_SELECTED_ARTWORK_FAILURE = "GET_SELECTED_ARTWORK_FAILURE";
export const GET_SELECTED_PORTFOLIO = "GET_SELECTED_PORTFOLIO";

//cart actions
export const LOAD_CART = "CREATE_CART";
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const DELETE_CART = "DELETE_CART";


export const REQUEST_ERROR = "REQUEST_ERROR";
