// export const SET_ALERT = 'SET_ALERT';
// export const REMOVE_ALERT = 'REMOVE_ALERT';

// export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
// export const REGISTER_FAIL = 'REGISTER_FAIL';

// export const USER_LOADED = 'USER_LOADED';
// export const ADMIN_LOADED = 'ADMIN_LOADED';
// export const AUTH_ERROR = 'AUTH_ERROR';

// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAIL = 'LOGIN_FAIL';

// export const LOGOUT = "LOGOUT";
// export const CLEAR_PROFILE = "CLEAR_PROFILE";

// //admin actions
// export const ADD_PORTFOLIO = 'ADD_PORTFOLIO';
// export const EDIT_PORTFOLIO = "EDIT_PORTFOLIO";
// export const DELETE_PORTFOLIO = "DELETE_PORTFOLIO";

// export const ADD_IMAGE = 'ADD_IMAGE';
// export const EDIT_IMAGE = "EDIT_IMAGE";
// export const DELETE_IMAGE = "DELETE_IMAGE";
// export const PORTFOLIO_ERROR = 'PORTFOLIO_ERROR';
// export const IMAGE_ERROR = 'IMAGE_ERROR';

// //store actions
// export const LOAD_IMAGES = 'LOAD_IMAGES';
// export const LOAD_GALLERY = 'LOAD_GALLERY';
// export const LOAD_PORTFOLIOS = 'LOAD_PORTFOLIOS';
// export const GET_IMAGE = "GET_IMAGE";
// export const GET_PORTFOLIO = "GET_PORTFOLIO";
// export const GET_SELECTED_ARTWORK_SUCCESS = "GET_SELECTED_ARTWORK_SUCCESS";
// export const CLEAR_SELECTED_ARTWORK = "CLEAR_SELECTED_ARTWORK";
// export const GET_SELECTED_ARTWORK_FAIL = "GET_SELECTED_ARTWORK_FAIL";
// export const GET_RELATED_ARTWORK_SUCCESS = "GET_RELATED_ARTWORK_SUCCESS";
// export const GET_RELATED_ARTWORK_FAIL = "GET_RELATED_ARTWORK_FAIL";
// export const CLEAR_RELATED_ARTWORK = "CLEAR_RELATED_ARTWORK";


// //shop actions

// // export const SEARCH_IMAGES_ERROR = "SEARCH_IMAGES_ERROR";
// // export const GET_ARTWORK_BY_TITLE_SEARCH = "GET_ARTWORK_BY_TITLE_SEARCH";
// // export const GET_ARTWORK_BY_PORTFOLIO_SEARCH = "GET_ARTWORK_BY_PORTFOLIO_SEARCH";
// // export const GET_ARTWORK_BY_PRICE_SEARCH = "GET_ARTWORK_BY_PRICE_SEARCH";
// // export const CLEAR_SEARCH = "CLEAR_SEARCH";


// //cart actions
// export const LOAD_CART = "LOAD_CART";
// export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
// export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";

// export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
// export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";

// export const CLEAR_CART = "CLEAR_CART";
// export const CART_ERROR = "CART_ERROR";

// export const APPLY_DISCOUNT_SUCCESS = "APPLY_DISCOUNT_SUCCESS";
// export const APPLY_DISCOUNT_FAIL = "APPLY_DISCOUNT_FAIL";


// //account actions
// export const INIT_ACCOUNT = "INIT_ACCOUNT";
// export const CLEAR_ACCOUNT = "CLEAR_ACCOUNT";
// export const LOAD_ACCOUNT = "GET_ACCOUNT";

// export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
// export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
// export const ACCOUNT_ERROR = "ACCOUNT_ERROR";

// export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS"
// export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL";

// export const ADD_PAYMENT_METHOD_SUCCESS = "ADD_PAYMENT_METHOD_SUCCESS";
// export const ADD_PAYMENT_METHOD_FAIL = "ADD_PAYMENT_METHOD_FAIL";

// export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
// export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

// //order actions
// export const ADD_TO_ORDER_SUCCESS = "ADD_TO_ORDER_SUCCESS";
// export const ADD_TO_ORDER_FAIL = "ADD_TO_ORDER_FAIL";

// export const REMOVE_FROM_ORDER_SUCCESS = "REMOVE_FROM_ORDER_SUCCESS";
// export const REMOVE_FROM_ORDER_FAIL = "REMOVE_FROM_ORDER_FAIL";

// export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
// export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";
// export const GET_ORDER = "GET_ORDER";
// export const GET_ORDERS = "GET_ORDERS";
// export const DELETE_ORDER = "DELETE_ORDER";
// export const UPDATE_ORDER = "UPDATE_ORDER";
// export const ORDER_ERROR = "ORDER_ERROR";


// //stripe payment actions
// export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
// export const PAYMENT_FAIL = "PAYMENT_FAIL";
// export const GET_STRIPE_TOKEN = "GET_STRIPE_TOKEN";


// export const REQUEST_ERROR = "REQUEST_ERROR";



export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";

//admin actions
export const ADD_PORTFOLIO = "ADD_PORTFOLIO";
export const EDIT_PORTFOLIO = "EDIT_PORTFOLIO";
export const DELETE_PORTFOLIO = "DELETE_PORTFOLIO";

export const ADD_IMAGE = "ADD_IMAGE";
export const EDIT_IMAGE = "EDIT_IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const PORTFOLIO_ERROR = "PORTFOLIO_ERROR";
export const IMAGE_ERROR = "IMAGE_ERROR";

//store actions
export const LOAD_IMAGES = "LOAD_IMAGES";
export const LOAD_GALLERY = "LOAD_GALLERY";
export const LOAD_PORTFOLIOS = "LOAD_PORTFOLIOS";
export const GET_IMAGE = "GET_IMAGE";

export const GET_RELATED_ARTWORK_FAIL = "GET_RELATED_ARTWORK_FAIL";
export const GET_RELATED_ARTWORK_SUCCESS = "GET_RELATED_ARTWORK_SUCCESS";
export const CLEAR_RELATED_ARTWORK = "CLEAR_RELATED_ARTWORK";
export const GET_PORTFOLIO = "GET_PORTFOLIO";
export const GET_SELECTED_ARTWORK_SUCCESS = "GET_SELECTED_ARTWORK_SUCCESS";
export const CLEAR_SELECTED_ARTWORK = "CLEAR_SELECTED_ARTWORK";
export const GET_SELECTED_ARTWORK_FAIL = "GET_SELECTED_ARTWORK_FAIL";

export const GET_ARTWORK_BY_TITLE_SEARCH = "GET_ARTWORK_BY_TITLE_SEARCH";
export const GET_ARTWORK_BY_PORTFOLIO_SEARCH ="GET_ARTWORK_BY_PORTFOLIO_SEARCH";
export const GET_ARTWORK_BY_PRICE_SEARCH = "GET_ARTWORK_BY_PRICE_SEARCH";
export const SEARCH_IMAGES_ERROR = "SEARCH_IMAGES_ERROR";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
//cart actions
export const LOAD_CART = "LOAD_CART";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";

export const CLEAR_CART = "CLEAR_CART";
export const CART_ERROR = "CART_ERROR";

export const APPLY_DISCOUNT_SUCCESS = "APPLY_DISCOUNT_SUCCESS";
export const APPLY_DISCOUNT_FAIL = "APPLY_DISCOUNT_FAIL";


//account actions
export const INIT_ACCOUNT = "INIT_ACCOUNT";
export const CLEAR_ACCOUNT = "CLEAR_ACCOUNT";
export const LOAD_ACCOUNT = "GET_ACCOUNT";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const ACCOUNT_ERROR = "ACCOUNT_ERROR";

export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAIL = "ADD_ADDRESS_FAIL";


export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";



//order actions
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const CREATE_PAYMENT_INTENT_SUCCESS = "CREATE_PAYMENT_INTENT_SUCCESS";
export const CREATE_PAYMENT_INTENT_FAIL = "CREATE_PAYMENT_INTENT_FAIL";

export const INIT_PAYMENT_INTENT_SUCCESS = "INIT_PAYMENT_INTENT_SUCCESS";
export const INIT_PAYMENT_INTENT_FAIL = "INIT_PAYMENT_INTENT_FAIL";

export const ADD_PAYMENT_METHOD_SUCCESS = "ADD_PAYMENT_METHOD_SUCCESS";
export const ADD_PAYMENT_METHOD_FAIL = "ADD_PAYMENT_METHOD_FAIL";

export const GET_ORDER = "GET_ORDER";
export const GET_ORDERS = "GET_ORDERS";
export const CLEAR_CURRENT_ORDER = "CLEAR_CURRENT_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const ORDER_ERROR = "ORDER_ERROR";

//stripe payment actions
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";

export const REQUEST_ERROR = "REQUEST_ERROR";
