import axios from "axios";
import {
  CREATE_ORDER_SUCCESS,
  CREATE_ORDER_FAIL,
  GET_ORDER,
  GET_ORDERS,
  DELETE_ORDER,
  UPDATE_ORDER,
  ORDER_ERROR,
  PAYMENT_SUCCESS,
  PAYMENT_FAIL,
  GET_STRIPE_TOKEN
} from "./types";
